defaults: &defaults
  :address: smtp.library.ucsb.edu
  :domain: library.ucsb.edu
  :port: 25
  :enable_starttls_auto: true
  :user_name: <%= Rails.application.secrets.smtp_user %>
  :password: <%= Rails.application.secrets.smtp_password %>

development:
  <<: *defaults

staging:
  <<: *defaults

production:
  address: smtp.gmail.com,
  port: 587,
  authentication: plain,
  enable_starttls_auto: true 
  user_name: <%= Rails.application.secrets.smtp_user %>
  password: <%= Rails.application.secrets.smtp_password %>

