- name: provision basic alex2 vagrant box
  hosts: vagrant
  remote_user: vagrant
  vars:
      capistrano_user: vagrant
      capistrano_group: vagrant
      # Add keys to the list below for anyone who will cap deploy to the vm
      # see http://docs.ansible.com/ansible/authorized_key_module.html
      capistrano_keys:
          - https://github.com/acozine.keys
          - https://github.com/mark-dce.keys
      install_user: ucsb
      install_group: ucsb
      become_user: ucsb
      install_path: /opt/install
      project_name: alex2
      rails_env: production
      server_name: vagrant.localhost
      solr_context: hydra
  roles:
    - { role: vagrant, sudo: yes }
    - { role: housekeeping, sudo: yes }
    - { role: ruby }
    - { role: hydra-stack }
    - { role: services }
    - { role: passenger, sudo: yes }
    - { role: marmotta }
    - { role: app-config, sudo: yes }
