- hosts: localhost
  connection: local
  gather_facts: False
  roles:
      - launch_ec2

- hosts: ec2hosts
  name: configuration
  user: ubuntu
  gather_facts: true  
  vars:
    ec2_vol_1: "{{ hostvars['localhost'].ec2_vol }}"
  roles:
    - { role: housekeeping, sudo: yes }
    - { role: ruby }
    - { role: hydra-stack }
    - { role: services }
    - { role: passenger, sudo: yes }
    - { role: app-config, sudo: yes }
    - { role: ec2, sudo: yes }
