- name: provision basic vagrant box
  hosts: default
  remote_user: vagrant
  roles:
    - { role: vagrant, sudo: yes }
    - { role: housekeeping, sudo: yes }
    - { role: ruby }
    - { role: services }
    - { role: imagemagick }
    - { role: ffmpeg }
    - { role: dev-box }
