- name: provision basic vagrant box
  hosts: vagrant
  remote_user: vagrant
  roles:
    - { role: housekeeping, sudo: yes }
    - { role: vagrant }
    - { role: ruby }
    - { role: hydra-stack }
    - { role: services }
    - { role: passenger, sudo: yes }
    - { role: app-config, sudo: yes }
