---
# roles/ldap/tasks/main.yml
- name: add shared ldap config
  become: yes
  template: src=ldap.yml.j2 dest={{ config_path }}/ldap.yml \
            owner={{ deploy_user }} group={{ deploy_group }} backup=no
