---
- name: create apache vhosts file
  template: src=apache_config.j2 dest=/etc/httpd/conf.d/{{ project_name }}.conf owner=root group=root backup=no

#- name: remove default apache site
#  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent

