---
- name: add log rotation for production logs
  template: src=logrotate-rails.j2 dest=/etc/logrotate.d/rails

- name: add log rotation for catalina.out (tomcat/fedora/solr logs)
  template: src=logrotate-tomcat dest=/etc/logrotate.d/tomcat7 backup=yes

# use capistrano to deploy the code, migrate the database, restart apache
# TODO: generate secrets for the config files that need them

#- name: generate a secret
  # run rake secret, direct output to environment variable SECRET_KEY_BASE
  