---
- name: symlink runuser
  become: yes
  file: src=/usr/sbin/runuser dest=/usr/bin/runuser state=link

- name: initialize postgres db
  become: yes
  command: postgresql-setup initdb

- name: start postgres
  become: yes
  service: name=postgresql enabled=yes state=started
  
- name: set postgres password
  become: yes
  shell: cd /opt && sudo su - postgres -c "psql -U postgres -d postgres -c \"ALTER USER postgres WITH PASSWORD '{{ pg_pass }}';\""

- name: configure md5 security
  become: yes
  copy: src=pg_hba.conf dest=/var/lib/pgsql/data/pg_hba.conf group=postgres owner=postgres backup=yes

- name: restart postgres server
  become: yes
  service: name=postgresql state=restarted

- name: create pg hydra user
  postgresql_user: name={{ hydra_pg_user }} password={{ hydra_pg_pass }} role_attr_flags=CREATEDB state=present login_user=postgres login_password={{ pg_pass }}

- name: create pg hydra database
  postgresql_db: name={{ hydra_db }} state=present owner={{ hydra_pg_user }} login_user={{ hydra_pg_user }} login_password={{ hydra_pg_pass }}

