---
deploy_user: deploy
deploy_group: deploy
deploy_keys:
    - https://github.com/acozine.keys
    - https://github.com/jcoyne.keys
project_name: sufia-project
project_base: /opt
install_path: "{{ project_base }}/install"
