---
capistrano_user: deploy
capistrano_group: deploy
capistrano_keys:
    - https://github.com/acozine.keys
    - https://github.com/jcoyne.keys
install_path: /opt/install
project_name: sufia-project
