---
- name: install ffmpeg libraries
  become: yes
  yum: name={{ item }} state=present
  with_items:
      - autoconf
      - automake
      - cmake
      - freetype-devel
      - gcc
      - gcc-c++
      - git
      - libtool
      - make
      - mercurial
      - nasm
      - pkgconfig
      - zlib-devel

- name: remove package ffmpeg
  become: yes
  yum: name=ffmpeg state=absent

- name: create sources dir
  become: yes
  file: owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} state=directory path={{ ffmpeg_path }}
  register: ffmpeg_path={{ install_path }}/ffmpeg_sources

- name: ff add ldconfig for /usr/local/lib
  become: yes
  copy: dest=/etc/ld.so.conf.d/usr-local.conf content=/usr/local/lib owner=root group=root mode=0644
