---
- name: link media libraries built from source
  become: yes
  shell: /usr/sbin/ldconfig

- name: clone ffmpeg source
  git: repo=https://github.com/FFmpeg/FFmpeg.git \
       depth=1 dest={{ ffmpeg_path }}/ffmpeg force=yes

- name: configure ffmpeg
  environment:
    PKG_CONFIG_PATH: /usr/local/lib/pkgconfig
  shell: ./configure --extra-libs="-ldl" --enable-gpl --enable-nonfree --enable-libfdk_aac --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 \
         chdir={{ ffmpeg_path }}/ffmpeg

- name: make ffmpeg
  command: make \
           chdir={{ ffmpeg_path }}/ffmpeg

- name: install ffmpeg
  become: yes
  command: make install \
           chdir={{ ffmpeg_path }}/ffmpeg

- name: clean the ffmpeg repo
  become: yes
  command: make distclean \
           chdir={{ ffmpeg_path }}/ffmpeg

- name: link new ffmpeg
  become: yes
  shell: /usr/sbin/ldconfig
