---
- name: download fdk-aac source
  become: yes
  git: repo=git://git.code.sf.net/p/opencore-amr/fdk-aac depth=1 owner={{ install_user }} group={{ install_group }} dest={{ ffmpeg_path }}/fdk-aac

- name: clean the repo
  shell: cd {{ ffmpeg_path }}/fdk-aac && autoreconf -fiv

- name: configure fdk-aac
  become: yes
  shell: cd {{ ffmpeg_path }}/fdk-aac && ./configure --prefix="$HOME/ffmpeg_build" --disable-shared creates={{ ffmpeg_path }}/fdk-aac/Makefile

- name: make fdk-aac
  become: yes
  shell: cd {{ ffmpeg_path }}/fdk-aac && make 

- name: install fdk-aac
  sudo: yes
  shell: cd {{ ffmpeg_path }}/fdk-aac && make install
