---
- name: clone fdk-aac source
  git: repo=http://git.code.sf.net/p/opencore-amr/fdk-aac \
       depth=1 accept_hostkey=yes dest={{ ffmpeg_path }}/fdk-aac force=yes

- name: generate the configure script
  command: ./autogen.sh
           chdir={{ ffmpeg_path }}/fdk-aac

- name: configure fdk-aac
  command: ./configure --disable-shared --prefix=/usr/local \
           chdir={{ ffmpeg_path }}/fdk-aac
           creates={{ ffmpeg_path }}/fdk-aac/Makefile

- name: make fdk-aac
  command: make \
           chdir={{ ffmpeg_path }}/fdk-aac

- name: install fdk-aac
  become: yes
  command: make install \
           chdir={{ ffmpeg_path }}/fdk-aac

- name: clean the fkd-aac repo
  become: yes
  command: make distclean \
           chdir={{ ffmpeg_path }}/fdk-aac
