---
- name: download libmp3lame source
  get_url:
    url: https://downloads.sourceforge.net/sourceforge/lame/lame-3.99.5.tar.gz
    dest: "{{ ffmpeg_path }}/lame-3.99.5.tar.gz"

- name: unzip libmp3lame source
  unarchive:
    src: "{{ ffmpeg_path }}/lame-3.99.5.tar.gz"
    dest: "{{ ffmpeg_path }}/"
    creates: "{{ ffmpeg_path }}/lame-3.99.5/compile.c"
    copy: no

- name: configure libmp3lame
  command: ./configure --disable-shared --enable-nasm --prefix=/usr/local
  args:
    chdir: "{{ ffmpeg_path }}/lame-3.99.5"
    creates: "{{ ffmpeg_path }}/lame-3.99.5/Makefile"

- name: make libmp3lame
  command: make
  args:
    chdir: "{{ ffmpeg_path }}/lame-3.99.5"

- name: install libmp3lame
  become: yes
  command: make install
  args:
    chdir: "{{ ffmpeg_path }}/lame-3.99.5"

- include: ldconfig.yml
