---
- name: download ogg source
  get_url:
    url: http://downloads.xiph.org/releases/ogg/libogg-{{ ogg_ver }}.tar.gz
    dest: "{{ ffmpeg_path }}/libogg-{{ ogg_ver }}.tar.gz"
    sha256sum: "{{ ogg_256 }}"

- name: unzip ogg source
  unarchive:
    src: "{{ ffmpeg_path }}/libogg-{{ ogg_ver }}.tar.gz"
    dest: "{{ ffmpeg_path }}/"
    creates: "{{ ffmpeg_path }}/libogg-{{ ogg_ver }}/compile.c"
    copy: no

- name: configure ogg
  command: ./configure --prefix=/usr/local
  args:
    chdir: "{{ ffmpeg_path }}/libogg-{{ ogg_ver }}"
    creates: "{{ ffmpeg_path }}/libogg-{{ ogg_ver }}/Makefile"

- name: make ogg
  command: make
  args:
    chdir: "{{ ffmpeg_path }}/libogg-{{ ogg_ver }}"

- name: install ogg
  become: yes
  command: make install
  args:
    chdir: "{{ ffmpeg_path }}/libogg-{{ ogg_ver }}"

- include: ldconfig.yml
