---
- name: download ogg source
  become: yes
  get_url: url=http://downloads.xiph.org/releases/ogg/libogg-1.3.1.tar.gz owner={{ install_user }} group={{ install_group }} dest={{ ffmpeg_path }}/libogg-1.3.1.tar.gz

- name: unzip ogg source
  become: yes
  unarchive: src={{ ffmpeg_path }}/libogg-1.3.1.tar.gz dest={{ ffmpeg_path }}/ creates={{ ffmpeg_path }}/libogg-1.3.1/compile.c copy=no

- name: configure ogg
  become: yes
  shell: cd {{ ffmpeg_path }}/libogg-1.3.1 && ./configure --prefix="$HOME/ffmpeg_build" --bindir="$HOME/bin" creates={{ ffmpeg_path }}/libogg-1.3.1/Makefile

- name: make ogg
  become: yes
  shell: cd {{ ffmpeg_path }}/libogg-1.3.1 && make 

- name: install ogg
  sudo: yes
  shell: cd {{ ffmpeg_path }}/libogg-1.3.1 && make install
