---
- name: download libopus source
  get_url:
    url: http://downloads.xiph.org/releases/opus/opus-{{ opus_ver }}.tar.gz
    dest: "{{ ffmpeg_path }}/opus-{{ opus_ver }}.tar.gz"
    sha256sum: "{{ opus_256 }}"

- name: unzip libopus source
  unarchive:
    src: "{{ ffmpeg_path }}/opus-{{ opus_ver }}.tar.gz"
    dest: "{{ ffmpeg_path }}/"
    creates: "{{ ffmpeg_path }}/opus-{{ opus_ver }}/compile.c"
    copy: no

- name: configure libopus
  command: ./configure --disable-shared --prefix=/usr/local
  args:
    chdir: "{{ ffmpeg_path }}/opus-{{ opus_ver }}"
    creates: "{{ ffmpeg_path }}/opus-{{ opus_ver }}/Makefile"

- name: make libopus
  command: make
  args:
    chdir: "{{ ffmpeg_path }}/opus-{{ opus_ver }}"

- name: install libopus
  become: yes
  command: make install
  args:
    chdir: "{{ ffmpeg_path }}/opus-{{ opus_ver }}"

- include: ldconfig.yml
