---
- name: download ogg source
  get_url: url=http://downloads.xiph.org/releases/ogg/libogg-1.3.1.tar.gz \
           dest={{ ffmpeg_path }}/libogg-1.3.1.tar.gz

- name: unzip ogg source
  unarchive: src={{ ffmpeg_path }}/libogg-1.3.1.tar.gz dest={{ ffmpeg_path }}/ \
             creates={{ ffmpeg_path }}/libogg-1.3.1/compile.c copy=no

- name: configure ogg
  command: ./configure --prefix=/usr/local \
           chdir={{ ffmpeg_path }}/libogg-1.3.1 \
           creates={{ ffmpeg_path }}/libogg-1.3.1/Makefile

- name: make ogg
  command: make \
           chdir={{ ffmpeg_path }}/libogg-1.3.1

- name: install ogg
  become: yes
  command: make install \
           chdir={{ ffmpeg_path }}/libogg-1.3.1
