---
- name: install libraries
  yum: name={{ item }} state=present
  with_items:
      - autoconf
      - automake
      - cmake
      - freetype-devel
      - gcc
      - gcc-c++
      - git
      - libtool
      - make
      - mercurial
      - nasm
      - pkgconfig
      - zlib-devel

- name: remove package ffmpeg
  yum: name=ffmpeg state=absent

- name: create sources dir
  file: owner={{ install_user }} group={{ install_group }} state=directory path={{ ffmpeg_path }}
  register: ffmpeg_path={{ install_path }}/ffmpeg_sources

#- set variables 