---
- name: download libvpx source
  get_url:
    url: https://github.com/webmproject/libvpx/archive/v{{ vpx_ver }}.tar.gz
    dest: "{{ install_path }}/libvpx-{{ vpx_ver }}.tar.gz"
    sha256sum: "{{ vpx_256 }}"

- name: unpack libvpx
  unarchive:
    copy: no
    src: "{{ install_path }}/libvpx-{{ vpx_ver }}.tar.gz"
    dest: "{{ ffmpeg_path }}"

- name: configure libvpx
  command: ./configure --disable-examples --prefix=/usr/local
  args:
    chdir: "{{ ffmpeg_path }}/libvpx-{{ vpx_ver }}"
    creates: "{{ ffmpeg_path }}/libvpx-{{ vpx_ver }}/Makefile"

- name: make libvpx
  command: make
  args:
    chdir: "{{ ffmpeg_path }}/libvpx-{{ vpx_ver }}"

- name: install libvpx
  become: yes
  command: make install
  args:
    chdir: "{{ ffmpeg_path }}/libvpx-{{ vpx_ver }}"

- name: clean the libvpx repo
  become: yes
  command: make distclean
  args:
    chdir: "{{ ffmpeg_path }}/libvpx-{{ vpx_ver }}"

- include: ldconfig.yml
