---
- name: download libvpx source
  git: repo=http://git.chromium.org/webm/libvpx.git depth=1 owner={{ install_user }} group={{ install_group }} dest={{ ffmpeg_path }}/libvpx

- name: configure libvpx
  shell: cd {{ ffmpeg_path }}/libvpx && ./configure --disable-examples creates={{ ffmpeg_path }}/libvpx/Makefile

- name: make libvpx
  shell: cd {{ ffmpeg_path }}/libvpx && make 

- name: install libvpx
  sudo: yes
  shell: cd {{ ffmpeg_path }}/libvpx && make install
