---
- name: download libvorbis source
  get_url:
    url: http://downloads.xiph.org/releases/vorbis/libvorbis-{{ vorbis_ver }}.tar.xz
    dest: "{{ ffmpeg_path }}/libvorbis-{{ vorbis_ver }}.tar.xz"
    sha256sum: "{{ vorbis_256 }}"

- name: unzip libvorbis source
  unarchive:
    src: "{{ ffmpeg_path }}/libvorbis-{{ vorbis_ver }}.tar.xz"
    dest: "{{ ffmpeg_path }}"
    creates: "{{ ffmpeg_path }}/libvorbis-{{ vorbis_ver }}/compile.c"
    copy: no

- name: configure libvorbis
  command: ./configure --prefix=/usr/local
  args:
    chdir: "{{ ffmpeg_path }}/libvorbis-{{ vorbis_ver }}"
    creates: "{{ ffmpeg_path }}/libvorbis-{{ vorbis_ver }}/Makefile"

- name: make libvorbis
  command: make
  args:
    chdir: "{{ ffmpeg_path }}/libvorbis-{{ vorbis_ver }}"

- name: install libvorbis
  become: yes
  command: make install
  args:
    chdir: "{{ ffmpeg_path }}/libvorbis-{{ vorbis_ver }}"

- include: ldconfig.yml
