---
- name: clone libvpx source
  git: repo=https://chromium.googlesource.com/webm/libvpx.git \
       depth=1 dest={{ ffmpeg_path }}/libvpx force=yes

- name: configure libvpx
  command: ./configure --disable-examples --prefix=/usr/local \
           chdir={{ ffmpeg_path }}/libvpx \
           creates={{ ffmpeg_path }}/libvpx/Makefile

- name: make libvpx
  command: make \
           chdir={{ ffmpeg_path }}/libvpx

- name: install libvpx
  become: yes
  command: make install \
           chdir={{ ffmpeg_path }}/libvpx

- name: clean the libvpx repo
  become: yes
  command: make distclean \
           chdir={{ ffmpeg_path }}/libvpx

- include: ldconfig.yml
