---
- name: clone x264 source
  git:
    repo: "https://git.videolan.org/git/x264.git"
    dest: "{{ ffmpeg_path }}/x264"
    force: yes
    version: "{{ x264_commit }}"

- name: configure x264
  command: ./configure --enable-static --prefix=/usr/local
  args:
    chdir: "{{ ffmpeg_path }}/x264"

- name: make x264
  command: make
  args:
    chdir: "{{ ffmpeg_path }}/x264"

- name: install x264
  become: yes
  command: make install
  args:
    chdir: "{{ ffmpeg_path }}/x264"

- name: clean the x264 repo
  become: yes
  command: make distclean
  args:
    chdir: "{{ ffmpeg_path }}/x264"
