---
- name: download yasm source
  become: yes
  get_url: url=http://www.tortall.net/projects/yasm/releases/yasm-1.2.0.tar.gz owner={{ install_user }} group={{ install_group }} dest={{ ffmpeg_path }}/yasm-1.2.0.tar.gz

- name: unzip yasm source
  become: yes
  unarchive: src={{ ffmpeg_path }}/yasm-1.2.0.tar.gz dest={{ ffmpeg_path }}/ creates={{ ffmpeg_path }}/yasm-1.2.0/compile.c copy=no

- name: configure yasm
  become: yes
  shell: cd {{ ffmpeg_path }}/yasm-1.2.0 && ./configure --prefix="$HOME/ffmpeg_build" --bindir="$HOME/bin" creates={{ ffmpeg_path }}/yasm-1.2.0/Makefile

- name: make yasm
  become: yes
  shell: cd {{ ffmpeg_path }}/yasm-1.2.0 && make 

- name: install yasm
  sudo: yes
  shell: cd {{ ffmpeg_path }}/yasm-1.2.0 && make install
