---
- name: debug
  shell: whoami
  register: user

- name: what user am I
  debug: var=user

- name: clone yasm source
  git: repo=https://github.com/yasm/yasm.git \
       depth=1 dest={{ ffmpeg_path }}/yasm force=yes

- name: reconfigure the yasm repo
  command: ./autogen.sh --prefix=/usr/local \
           chdir={{ ffmpeg_path }}/yasm

- name: make yasm
  command: make \
           chdir={{ ffmpeg_path }}/yasm

- name: install yasm
  become: yes
  command: make install \
           chdir={{ ffmpeg_path }}/yasm

- name: clean the yasm repo
  become: yes
  command: make distclean \
           chdir={{ ffmpeg_path }}/yasm

- include: ldconfig.yml
