---
- name: debug
  shell: whoami
  register: user

- name: what user am I
  debug: var=user

- name: download yasm source
  get_url:
    url: https://www.tortall.net/projects/yasm/releases/yasm-{{ yasm_ver }}.tar.gz
    dest: "{{ install_path }}/yasm-{{ yasm_ver }}.tar.gz"
    sha256sum: "{{ yasm_256 }}"

- name: unpack yasm source
  unarchive:
    copy: no
    src: "{{ install_path }}/yasm-{{ yasm_ver }}.tar.gz"
    dest: "{{ ffmpeg_path }}"

- name: configure yasm
  command: ./configure --prefix=/usr/local
  args:
    chdir: "{{ ffmpeg_path }}/yasm-{{ yasm_ver }}"

- name: make yasm
  command: make
  args:
    chdir: "{{ ffmpeg_path }}/yasm-{{ yasm_ver }}"

- name: install yasm
  become: yes
  command: make install
  args:
    chdir: "{{ ffmpeg_path }}/yasm-{{ yasm_ver }}"

- name: clean the yasm repo
  become: yes
  command: make distclean
  args:
    chdir: "{{ ffmpeg_path }}/yasm-{{ yasm_ver }}"

- include: ldconfig.yml
