---
# roles/smtp/tasks/main.yml
- name: add smtp shared config file
  become: yes
  template: src=smtp.yml.j2 dest={{ config_path }}/smtp.yml \
            owner={{ deploy_user }} group={{ deploy_group }} backup=no
