---
- name: create marmotta group
  group: name={{ marmotta_group }} state=present
  sudo: yes

- name: create marmotta user
  user: name={{ marmotta_user }} group={{ marmotta_group }} shell=/bin/bash home=/opt/marmotta createhome=yes state=present
  sudo: yes

- name: create marmotta_home
  file: path={{ marmotta_home }} state=directory

- name: download marmotta
  get_url: url=http://mirror.cc.columbia.edu/pub/software/apache/marmotta/{{ marmotta_version }}/apache-marmotta-{{ marmotta_version }}-webapp.tar.gz \
           sha256sum={{ marmotta_sha }} \
           owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} \
           dest={{ install_path }}/apache-marmotta-{{ marmotta_version }}-webapp.tar.gz

- name: unpack marmotta
  unarchive: src={{ install_path }}/apache-marmotta-{{ marmotta_version }}-webapp.tar.gz dest={{ install_path }}/ \
             creates={{ install_path }}/apache-marmotta-{{ marmotta_version }}/marmotta.war copy=no

- name: install marmotta
  become: yes
  command: cp {{ install_path }}/apache-marmotta-{{ marmotta_version }}/marmotta.war /var/lib/tomcat/webapps/marmotta.war \
           creates=/var/lib/tomcat/webapps/marmotta.war

- name: set ownership on marmotta.war
  become: yes
  command: chown tomcat:tomcat /var/lib/tomcat/webapps/marmotta.war

- name: set permissions for marmotta_home
  become: yes
  file: path={{ marmotta_home }} owner=marmotta group=marmotta mode=0755 state=directory recurse=yes

- name: set marmotta system config properties (linux)
  become: yes
  template: src=system-config.properties.j2 dest={{ marmotta_home }}/system-config.properties \
            owner=tomcat group=tomcat backup=no mode=0600

# Currently Marmotta tries to install a
# logging library that conflicts with Solr's, so for now we're just
# removing that library. 
# Check - is the library installed before Marmotta runs?
# If not, restart tomcat after installing Marmotta, then remove
# the library, then restart Tomcat again.

- name: remove log4j-over-slf4j.jar
  file: path={{ item }} state=absent
  become: yes
  with_items:
    - /var/lib/tomcat/webapps/marmotta/WEB-INF/lib/log4j-over-slf4j-1.7.7.jar

- name: restart tomcat
  become: yes
  service: name=tomcat enabled=yes state=restarted
