---
- name: create marmotta group
  group: name={{ marmotta_group }} state=present
  become: yes

- name: create marmotta user
  become: yes
  user: name={{ marmotta_user }} group={{ marmotta_group }} shell=/bin/bash \
        home={{ marmotta_home }} createhome=yes state=present

- name: create marmotta_home
  file: path={{ marmotta_home }} state=directory

- name: download marmotta
  get_url: url=http://mirror.cc.columbia.edu/pub/software/apache/marmotta/{{ marmotta_ver }}/apache-marmotta-{{ marmotta_ver }}-webapp.tar.gz \
           sha256sum={{ marmotta_256 }} \
           owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} \
           dest={{ install_path }}/apache-marmotta-{{ marmotta_ver }}-webapp.tar.gz

- name: unpack marmotta
  unarchive: src={{ install_path }}/apache-marmotta-{{ marmotta_ver }}-webapp.tar.gz dest={{ install_path }}/ \
             creates={{ install_path }}/apache-marmotta-{{ marmotta_ver }}/marmotta.war copy=no

- name: install marmotta
  become: yes
  command: cp {{ install_path }}/apache-marmotta-{{ marmotta_ver }}/marmotta.war {{ tomcat }}/webapps/marmotta.war \
           creates={{ tomcat }}/webapps/marmotta.war

- name: set ownership on marmotta.war
  become: yes
  file: path={{ tomcat }}/webapps/marmotta.war owner=tomcat group=tomcat

- name: set permissions for marmotta_home
  become: yes
  file: path={{ marmotta_home }} owner=marmotta group=marmotta mode=0755 state=directory recurse=yes

- name: set marmotta system config properties
  become: yes
  template: src=system-config.properties.j2 dest={{ marmotta_home }}/system-config.properties \
            owner=tomcat group=tomcat backup=no mode=0600

- name: restart tomcat
  service: name=tomcat enabled=yes state=restarted

- wait_for: path={{ tomcat }}/webapps/marmotta/WEB-INF/lib/log4j-over-slf4j-1.7.7.jar

# Currently Marmotta tries to install a
# logging library that conflicts with Solr's, so for now we're just
# removing that library.
# Check - is the library installed before Marmotta runs?
# If not, restart tomcat after installing Marmotta, then remove
# the library, then restart Tomcat again.

- name: remove log4j-over-slf4j.jar
  become: yes
  file: path={{ item }} state=absent
  with_items:
    - "{{ tomcat }}/webapps/marmotta/WEB-INF/lib/log4j-over-slf4j-1.7.7.jar"

# Otherwise subsequent runs will hang on the "wait_for" above
- file: path={{ tomcat }}/webapps/marmotta/WEB-INF/lib/log4j-over-slf4j-1.7.7.jar state=touch

- name: restart tomcat
  become: yes
  service: name=tomcat enabled=yes state=restarted
