---
# roles/ezid/tasks/main.yml
- name: add ezid shared config
  become: yes
  template: src=ezid.yml.j2 dest=/opt/{{ project_name }}/shared/config/ezid.yml \
            owner={{ deploy_user }} group={{ deploy_group }} backup=no
