---
# roles/ezid/tasks/main.yml
- name: add ezid shared config
  become: yes
  template: src=ezid.yml.j2 dest={{ config_path }}/ezid.yml \
            owner={{ deploy_user }} group={{ deploy_group }} backup=no
