---
# roles/ezid/tasks/main.yml
- name: write ezid secrets to secrets.yml
  become: yes
  lineinfile:
      backup: yes
      dest: "{{ config_path }}/secrets.yml"
      state: present
      insertafter: ^default
      line: "{{ item }}"
  with_items:
      - "  ezid_default_shoulder: {{ ezid_default_shoulder }}"
      - "  ezid_pass: {{ ezid_password }}"
      - "  ezid_user: {{ ezid_user }}"

- name: write ezid hostname/port to application.yml
  become: yes
  lineinfile:
      backup: yes
      dest: "{{ config_path }}/application.yml"
      state: present
      insertafter: ^default
      line: "{{ item }}"
  with_items:
      - "  ezid_host: {{ ezid_host }}"
      - "  ezid_port: {{ ezid_port }}"
