---
- name: update apt cache
  apt: update_cache=yes

- name: upgrade apt packages
  apt: upgrade=full

- name: install dev tools and libraries
  apt: name={{ item}} state=latest
  with_items:
    - build-essential
    - git
    - git-core
    - curl
    - openssl
    - libreadline6
    - libreadline6-dev
    - zlib1g
    - zlib1g-dev
    - libssl-dev
    - libyaml-dev
    - libxml2-dev
    - libxslt-dev
    - autoconf
    - libc6-dev
    - ncurses-dev
    - automake
    - libtool
    - bison
    - subversion
    - pkg-config
    - libmagickwand-dev
    - imagemagick
    - libcurl4-openssl-dev
    - libxvidcore-dev
    - redis-server
    - xfsprogs
