---
- name: create install group
  group: name={{ install_group }} state=present

- name: create install user
  user: name={{ install_user }} group={{ install_group }} shell=/bin/bash createhome=yes state=present

- name: chown /opt
  file: owner={{ install_user }} group={{ install_group }} state=directory path=/opt

- name: create install directory
  file: owner={{ install_user }} group={{ install_group }} state=directory path={{ install_path }}

- name: create cap group
  group: name={{ capistrano_group }} state=present

- name: create cap user
  user: name={{ capistrano_user }} group={{ capistrano_group }} shell=/bin/bash createhome=yes state=present

- name: create cap directories
  file: path={{ item }} state=directory owner={{ capistrano_user }} group={{ capistrano_group }} 
  with_items:
    - /opt/{{ project_name }}/shared/config/initializers
    - /opt/{{ project_name }}/shared/log
    - /opt/{{ project_name }}/releases
    - /home/{{ capistrano_user }}/.ssh

- name: add keys for capistrano user
  authorized_key: user={{ capistrano_user }} key="{{ item }}" 
  with_items: "{{ capistrano_keys }}"
