---
# the rest of the imagemagick role is now exactly the same as the ubuntu version
# to integrate, we should be able to use the distro-neutral package approach
# with Ansible 2.0
- name: install IM libraries
  become: yes
  yum: name={{ item }} state=present
  with_items:
      - autoconf
      - automake
      - cmake
      - fontconfig-devel
      - freetype-devel
      - gcc
      - gcc-c++
      - lcms2-devel
      - libpng-devel
      - libtool
      - libtool-ltdl-devel
      - make
      - pkgconfig
      - xz
      - zlib-devel

- name: remove package imagemagick
  become: yes
  yum: name=imagemagick state=absent

- name: create IM sources dir
  become: yes
  file:
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    state: directory
    path: "{{ magick_path }}"

- name: IM add ldconfig for /usr/local/lib
  become: yes
  copy:
    dest: /etc/ld.so.conf.d/usr-local.conf
    content: /usr/local/lib
    owner: root
    group: root
    mode: 0644
