---
# Note: this code assumes that valid imagemagick releases are in tar-zip format.  It appears that future releases may switch to 7zip format...

# ImageMagick regularly removes old tarballs, so use a mirror
- name: download ImageMagick
  get_url:
    url: https://dl.bintray.com/homebrew/mirror/ImageMagick-6.9.3-6.tar.xz
    dest: "{{ magick_path }}/ImageMagick-{{ imagemagick_ver }}.tar.xz"
    sha256sum: "{{ imagemagick_256 }}"

- name: unpack ImageMagick
  unarchive:
    src: "{{ magick_path }}/ImageMagick-{{ imagemagick_ver }}.tar.xz"
    dest: "{{ magick_path }}/"
    copy: no

- name: configure ImageMagick
  environment:
    PKG_CONFIG_PATH: /usr/local/lib/pkgconfig
  command: ./configure --prefix=/usr/local --with-modules=yes
  args:
    chdir: "{{ magick_path }}/ImageMagick-{{ imagemagick_ver }}"

- name: make ImageMagick
  command: make
  args:
    chdir: "{{ magick_path }}/ImageMagick-{{ imagemagick_ver }}"

- name: install ImageMagick
  become: yes
  command: make install
  args:
    chdir: "{{ magick_path }}/ImageMagick-{{ imagemagick_ver }}"

- include: ldconfig.yml
