---
- name: download libpng source
  get_url:
    url: https://downloads.sourceforge.net/project/libpng/libpng{{ libpng_major }}/{{ libpng_ver }}/libpng-{{ libpng_ver }}.tar.xz
    dest: "{{ magick_path }}/libpng-{{ libpng_ver }}.tar.xz"
    sha256sum: "{{ libpng_256 }}"

- name: unzip libpng source
  unarchive:
    src: "{{ magick_path }}/libpng-{{ libpng_ver }}.tar.xz"
    dest: "{{ magick_path }}/"
    creates: "{{ magick_path }}/libpng-{{ libpng_ver }}"
    copy: no

- name: configure libpng
  command: ./configure
  args:
    chdir: "{{ magick_path }}/libpng-{{ libpng_ver }}"

- name: make libpng
  command: make
  args:
    chdir: "{{ magick_path }}/libpng-{{ libpng_ver }}"

- name: install libpng
  become: yes
  command: make install
  args:
    chdir: "{{ magick_path }}/libpng-{{ libpng_ver }}"

- include: ldconfig.yml
