---
- name: download libpng source
  get_url: url=http://downloads.sourceforge.net/project/libpng/libpng16/1.6.18/libpng-1.6.18.tar.gz dest={{ magick_path }}/libpng-1.6.18.tar.gz

- name: unzip libpng source
  unarchive: src={{ magick_path }}/libpng-1.6.18.tar.gz dest={{ magick_path }}/ creates={{ magick_path }}/libpng-1.6.18 copy=no

- name: configure libpng
  shell: cd {{ magick_path }}/libpng-1.6.18 && ./configure

- name: make libpng
  shell: cd {{ magick_path }}/libpng-1.6.18 && make 

- name: install libpng
  sudo: yes
  shell: cd {{ magick_path }}/libpng-1.6.18 && make install