---
- name: download libtiff source
  get_url:
    url: http://download.osgeo.org/libtiff/tiff-{{ libtiff_ver }}.tar.gz
    dest: "{{ magick_path }}/tiff-{{ libtiff_ver }}.tar.gz"
    sha256sum: "{{ libtiff_256 }}"

- name: unzip libtiff source
  unarchive:
    src: "{{ magick_path }}/tiff-{{ libtiff_ver }}.tar.gz"
    dest: "{{ magick_path }}/"
    creates: "{{ magick_path }}/tiff-{{ libtiff_ver }}"
    copy: no

- name: configure libtiff
  command: ./configure
  args:
    chdir: "{{ magick_path }}/tiff-{{ libtiff_ver }}"

- name: make libtiff
  command: make
  args:
    chdir: "{{ magick_path }}/tiff-{{ libtiff_ver }}"

- name: install libtiff
  become: yes
  command: make install
  args:
    chdir: "{{ magick_path }}/tiff-{{ libtiff_ver }}"

- include: ldconfig.yml
