---
- name: download libtiff source
  get_url: url=http://download.osgeo.org/libtiff/tiff-4.0.5.tar.gz dest={{ magick_path }}/tiff-4.0.5.tar.gz

- name: unzip libtiff source
  unarchive: src={{ magick_path }}/tiff-4.0.5.tar.gz dest={{ magick_path }}/ creates={{ magick_path }}/tiff-4.0.5 copy=no

- name: configure libtiff
  shell: cd {{ magick_path }}/tiff-4.0.5 && ./configure

- name: make libtiff
  shell: cd {{ magick_path }}/tiff-4.0.5 && make 

- name: install libtiff
  sudo: yes
  shell: cd {{ magick_path }}/tiff-4.0.5 && make install