---
- name: download openjpg source
  get_url: url=http://downloads.sourceforge.net/project/openjpeg.mirror/2.1.0/openjpeg-2.1.0.tar.gz dest={{ magick_path }}/openjpeg-2.1.0.tar.gz

- name: unzip openjpg source
  unarchive: src={{ magick_path }}/openjpeg-2.1.0.tar.gz dest={{ magick_path }}/ creates={{ magick_path }}/openjpeg-2.1.0 copy=no

- name: configure openjpg
  shell: cd {{ magick_path }}/openjpeg-2.1.0 && cmake ./

- name: make openjpg
  shell: cd {{ magick_path }}/openjpeg-2.1.0 && make 

- name: install openjpg
  sudo: yes
  shell: cd {{ magick_path }}/openjpeg-2.1.0 && make install
