---
- name: download openjpg source
  get_url:
    url: https://downloads.sourceforge.net/project/openjpeg.mirror/{{ openjpg_ver }}/openjpeg-{{ openjpg_ver }}.tar.gz
    dest: "{{ magick_path }}/openjpeg-{{ openjpg_ver }}.tar.gz"
    sha256sum: "{{ openjpg_256 }}"

- name: unzip openjpg source
  unarchive:
    src: "{{ magick_path }}/openjpeg-{{ openjpg_ver }}.tar.gz"
    dest: "{{ magick_path }}/"
    creates: "{{ magick_path }}/openjpeg-version.{{ openjpg_ver }}"
    copy: no

- name: configure openjpg
  command: cmake .
  args:
    chdir: "{{ magick_path }}/openjpeg-{{ openjpg_ver }}"

- name: make openjpg
  command: make
  args:
    chdir: "{{ magick_path }}/openjpeg-{{ openjpg_ver }}"

- name: install openjpg
  become: yes
  command:  make install
  args:
    chdir: "{{ magick_path }}/openjpeg-{{ openjpg_ver }}"

- include: ldconfig.yml
