---
- name: download fedora
  become: yes
  get_url: url=http://repo1.maven.org/maven2/org/fcrepo/fcrepo-webapp/4.1.0/fcrepo-webapp-4.1.0.war owner={{ install_user }} group={{ install_group }} dest={{ install_path }}/fcrepo-webapp-4.1.0.war

- name: make fedora data dir
  file: owner=tomcat7 group=tomcat7 state=directory path=/opt/fedora-data
  sudo: yes

- name: check fedora.war
  become: yes
  stat: path=/var/lib/tomcat7/webapps/fedora.war
  register: fedora_war

- name: copy over fedora.war
  sudo: yes
  command: cp {{ install_path }}/fcrepo-webapp-4.1.0.war /var/lib/tomcat7/webapps/fedora.war
  when: fedora_war.stat.exists == False

- name: create tomcat config and java options
  sudo: yes
  template: src=tomcat7.j2 dest=/etc/default/tomcat7 backup=yes 
# TODO: make Java options configurable at the time of the ansible run

- name: restart tomcat
  sudo: yes
  service: name=tomcat7 enabled=yes state=restarted
