---
- name: download fedora
  get_url: url=http://repo1.maven.org/maven2/org/fcrepo/fcrepo-webapp/{{ fedora_version }}/fcrepo-webapp-{{ fedora_version }}.war owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} dest={{ install_path }}/fcrepo-webapp-{{ fedora_version }}.war

- name: make fedora data dir
  file: owner=tomcat group=tomcat state=directory path=/opt/fedora-data
  become: yes

- name: check fedora.war
  stat: path=/var/lib/tomcat/webapps/fedora.war
  register: fedora_war

- name: copy over fedora.war
  become: yes
  command: cp {{ install_path }}/fcrepo-webapp-{{ fedora_version }}.war /var/lib/tomcat/webapps/fedora.war
  when: fedora_war.stat.exists == False

- name: create tomcat config and java options
  become: yes
  template: src=tomcat.j2 dest=/etc/tomcat/tomcat.conf backup=yes

- name: restart tomcat
  become: yes
  service: name=tomcat enabled=yes state=restarted
