---
- name: get JDK 1.8 tarball (as RPM file)
  command: curl -L  -H 'Cookie:oraclelicense=accept-securebackup-cookie'  -o jdk-8u51-linux-x64.rpm  http://download.oracle.com/otn-pub/java/jdk/8u51-b16/jdk-8u51-linux-x64.rpm
  args:
    creates: "{{ install_path }}/jdk-8u51-linux-x64.rpm"

- name: install JDK 1.8
  yum: name={{install_path }}/jdk-8u51-linux-x64.rpm state=present
#  args:
    #creates: "{{ jdk_download_path }}/jdk-{{ jdk8.jdk_version }}"
    #chdir:   "{{ jdk_download_path }}"
  #when: java_version == 8

#- name: install java 8
#  sudo: yes
#  yum: name=java-1.8.0python-psycopg2 update_cache=yes state=present

- name: download fedora
  become: yes
  get_url: url=http://repo1.maven.org/maven2/org/fcrepo/fcrepo-webapp/4.3.0/fcrepo-webapp-4.3.0.war owner={{ install_user }} group={{ install_group }} dest={{ install_path }}/fcrepo-webapp-4.3.0.war

- name: make fedora data dir
  file: owner=tomcat group=tomcat state=directory path=/opt/fedora-data
  sudo: yes

- name: check fedora.war
  become: yes
  stat: path=/var/lib/tomcat/webapps/fedora.war
  register: fedora_war

- name: copy over fedora.war
  sudo: yes
  command: cp {{ install_path }}/fcrepo-webapp-4.3.0.war /var/lib/tomcat/webapps/fedora.war
  when: fedora_war.stat.exists == False

- name: create tomcat config and java options
  sudo: yes
  template: src=tomcat.j2 dest=/etc/tomcat/tomcat.conf backup=yes 
# TODO: make Java options configurable at the time of the ansible run

- name: restart tomcat
  sudo: yes
  service: name=tomcat enabled=yes state=restarted
