---
- name: download fedora
  get_url: url=https://repo1.maven.org/maven2/org/fcrepo/fcrepo-webapp/{{ fedora_ver }}/fcrepo-webapp-{{ fedora_ver }}.war \
           owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} \
           sha256sum={{ fedora_256 }} \
           dest={{ install_path }}/fcrepo-webapp-{{ fedora_ver }}.war

- name: make fedora data dir
  file: owner=tomcat group=tomcat state=directory path=/opt/fedora-data
  become: yes

- name: check fedora.war
  stat: path={{ tomcat }}/webapps/fedora.war
  register: fedora_war

- name: copy over fedora.war
  become: yes
  command: cp {{ install_path }}/fcrepo-webapp-{{ fedora_ver }}.war {{ tomcat }}/webapps/fedora.war
  when: fedora_war.stat.exists == False

- name: create tomcat config and java options
  become: yes
  template: src=tomcat.j2 dest=/etc/tomcat/tomcat.conf backup=yes

- name: restart tomcat
  become: yes
  service: name=tomcat enabled=yes state=restarted
