---
- name: install tomcat packages
  sudo: yes
  yum: name={{ item }} state=present
  with_items:
      - tomcat
      - tomcat-webapps
      - tomcat-admin-webapps

- name: set tomcat to restart on reboot
  service: name=tomcat enabled=yes