---
- name: run redis-server
  service: name=redis-server state=started
  sudo: yes
  
- name: copy resque init script
  template: src=pool_q.j2 dest=/etc/init.d/resque-pool mode=0755
  sudo: yes

- name: start resque
  service: name=resque-pool state=started enabled=yes
  sudo: yes
